#!/bin/sh
export DEPLOYCODE_SILENT_ANSIBLE=0
export DEPLOYCODE_SILENT_INOTIFY=0

# Get Libraries.
# shellcheck source=usr/lib/libDeploy
# Priorize, the Internal Libraries - that's the default.
#if [ -f "/usr/lib/libDeploy" ]; then . /usr/lib/libDeploy; else . ./usr/lib/libDeploy; fi
# Priorize, the Development Libs in this folder, that's for Test envirement.
if [ -r "./usr/lib/libDeploy" ]; then . ./usr/lib/libDeploy; else . /usr/lib/libDeploy; fi

# Search for Playbook Folders..
pb_folder="/etc/deploycode/playbooks/"
[ ! -d "$pb_folder" ] && pb_folder="./etc/deploycode/playbooks"

[ ! -d "$pb_folder" ] && {
	echo "Error! Can not found the Playbook folder. Aborting Script." >&2
	exit 1
}

pb_vars_folder="/etc/deploycode/playbook-vars/"
[ ! -d "$pb_vars_folder" ] && pb_vars_folder="./etc/deploycode/playbook-vars/"
[ ! -d "$pb_vars_folder" ] && {
	echo "Error! Can not found the Playbook-Vars Folder folder ($pb_vars_folder) folder. Aborting Script." >&2
	exit 1
}

# The Config Folder in the Test Script is the Available Folder!
config_folder="/etc/deploycode/configs-available"
[ ! -d "$config_folder" ] && config_folder="./etc/deploycode/configs-available"
[ ! -d "$config_folder" ] && {
	echo "Error! Can not found the Config-Available folder ($config_folder) folder. Aborting Script." >&2
	exit 1
}

count_configs=$(count_folder_files "/etc/deploycode/configs-enabled" "conf" 2>/dev/null || echo 0)
echo "Activated Config Files: $count_configs"

### Get the Config name to test;
config_name="$1"
[ -z "$config_name" ] && {
	echo "Error: this is a Test Script. Overgive a File name Placed in $config_folder as First Parameter."
	echo "Listing. Give it without the .conf!"
	ls "$config_folder"
	echo "Aborting Script for this time."
	exit 1
}

cd "$config_folder" || exit 1
config_file="${config_folder}/${config_name}.conf"
[ ! -f "$config_file" ] && {
	echo "Error!: The File $config_file does not exist" >&2
	echo "Aborting Script" >&2
	exit 2
}
config_name=""

watch_for_run_pb "$config_file" "" "" "1"
